# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'whent1971@superrito.com'
  config.password       = '123456'
  config.integrator_key = '24faeb75-f7f7-4616-9b90-d15cf844b300'
  config.account_id     = '5262431'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v2'
end

